# Generated by Django 5.2 on 2025-05-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.CharField(default=1, unique=True),
        ),
    ]
