# Generated by Django 5.2 on 2025-05-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Company_picture',
            field=models.ImageField(default='images/company_default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='post_logo',
            field=models.ImageField(default='images/job_default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_app.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/avatar.svg', upload_to='images/avatars/'),
        ),
    ]
