# Generated by Django 5.2 on 2025-05-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_company_company_picture_job_post_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='founded',
            field=models.DateField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='founder',
            field=models.CharField(default='Aryush Khatri', max_length=400),
        ),
        migrations.AddField(
            model_name='company',
            name='main_service',
            field=models.CharField(default='IT Service', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='motto',
            field=models.TextField(default='Please insert Company short motto'),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
