# Generated by Django 5.2 on 2025-05-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_company_company_size_company_founded_company_founder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Company_picture',
            new_name='company_picture',
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
