# Generated by Django 5.2 on 2025-05-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_rename_company_picture_company_company_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_size',
            field=models.CharField(default='1+'),
        ),
    ]
