# Generated by Django 5.2 on 2025-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_alter_company_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_role',
            field=models.TextField(default='DO your job anyhow'),
        ),
    ]
