# Generated by Django 5.2 on 2025-05-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_job_job_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_role',
            new_name='job_responsibility',
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
