# Generated by Django 5.2 on 2025-05-06 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_rename_job_role_job_job_responsibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='address',
            field=models.CharField(default='address', max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='apply',
            name='full_name',
            field=models.CharField(default='fullname', max_length=300),
        ),
        migrations.AddField(
            model_name='apply',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_app.job'),
        ),
        migrations.AddField(
            model_name='apply',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
